name: k8s deployments

on: [push]

jobs:
  creating-docker-image:
    runs-on: self-hosted
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Creating Tag for docker image
        id: tag
        run: |
          TAG=$(date +%h%d%H%M%S)
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Creating docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: .docker/Dockerfile
          tags: prasannakumar0302/nginx:${{steps.tag.outputs.tag}}
          
      - name: creating pod file
        shell: bash
        run: |
          echo 'apiVersion: v1
          kind: Pod
          metadata:
            name: my-nginx-pod
            labels:
              app: web-app
              type: front-end
          spec:
            containers:
              - name: nginx-container
                image: prasannakumar0302/nginx:${{steps.tag.outputs.tag}}' > pod.yml
          cat pod.yml
          cp -r pod.yml /home/ec2-user/pod

      - name: applying pod definition file
        run: |
          sudo su -
          kubectl delete pod my-nginx-pod
          kubectl create -f /home/ec2-user/pod/pod.yml


